### ISSUE TITLE
Security issue:

### ISSUE THREAD

**Issue by imizaac** [klayveR/poe-log-monitor#6]
always-tail2 has an insecure dependency. 

Would you like me to resolve this? 

I really appreciate the work you have done in this project.

**Comment by klayveR** [comment]
I believe this is no longer an issue in the [develop](https://github.com/klayveR/poe-log-monitor/tree/develop) branch, which should be merged but I forgot I refactored this a while ago. If you find any security issues in there feel free to resolve them, help is always appreciated.
